name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # Or your default branch

env:
  # TODO: Replace with your GCP Project ID
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  # TODO: Replace with your Artifact Registry repository name
  GAR_REPOSITORY: nextjs-cloudrun-template-repo
  # TODO: Replace with the region of your Artifact Registry repository
  GAR_REGION: us-central1 # Example region
  # TODO: Replace with your Cloud Run service name
  CLOUD_RUN_SERVICE_NAME: nextjs-cloudrun-template-service
  # TODO: Replace with the region of your Cloud Run service
  CLOUD_RUN_REGION: us-central1 # Example region
  # TODO: Replace with your Workload Identity Provider
  WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
  # TODO: Replace with your Service Account email
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.WIF_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authorize Docker push
      run: gcloud auth configure-docker ${{ env.GAR_REGION }}-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build \
          --tag "${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }}" \
          .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push "${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }}"

  deploy:
    name: Deploy to Cloud Run
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.WIF_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.CLOUD_RUN_SERVICE_NAME }}
        region: ${{ env.CLOUD_RUN_REGION }}
        # Use the image pushed in the previous job
        image: ${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }}
        # Optional: set environment variables
        # env_vars: |
        #   KEY1=VALUE1
        #   KEY2=VALUE2
        flags: '--allow-unauthenticated' # Allow public access, adjust as needed

    # If required, output the URL of the deployed service
    - name: Show deployed URL
      run: echo "Deployed to ${{ steps.deploy.outputs.url }}"
